# -*- coding: utf-8 -*-
"""Calles San Miguel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFZHmAJXppDU9UJ79Ka6xenCTvHFmqZR
"""

# ==========================================
# Jupyter Notebook: Extracción de Malla Vial
# Comuna: San Miguel, Santiago, Chile
# Autor: Gerardo Ureta, PhD(c) en Industria Inteligente, PUCV
# ==========================================

# 1. Instalación de librerías (ejecutar una vez)

# 2. Importación de librerías
import osmnx as ox
import geopandas as gpd

# Configuración opcional
ox.settings.log_console = True
ox.settings.use_cache = True

# 3. Definir área de estudio
place_name = "San Miguel, Santiago, Chile"

# 4. Descargar red vial desde OpenStreetMap
# network_type="drive" -> solo calles transitables por vehículos
G = ox.graph_from_place(place_name, network_type='drive')

# 5. Convertir grafo a GeoDataFrames
nodes, edges = ox.graph_to_gdfs(G)

# 6. Revisar estructura
print(edges.head())
print(edges.crs)

# 7. Reproyectar a sistema de coordenadas adecuado para Chile
# WGS84 -> EPSG:4326 (por defecto)
# Proyección recomendada: EPSG:32719 (UTM Zona 19 Sur)
edges_proj = edges.to_crs(epsg=32719)

# 8. Guardar como Shapefile
output_path = "malla_vial_san_miguel.shp"
edges_proj.to_file(output_path)

print(f"Archivo guardado en: {output_path}")

# 9. (Opcional) Visualización rápida
edges_proj.plot(figsize=(10,10))

# ==========================================
# Notas técnicas:
# - Fuente de datos: OpenStreetMap
# - Precisión depende del mapeo colaborativo
# - Puede filtrarse por tipo de vía (highway)
# ==========================================

# 10. Filtrar tipos de calles
# Ejemplo: excluir caminos menores
if 'highway' in edges.columns:
    edges_filtrado = edges[edges['highway'].isin(['primary','secondary','tertiary','residential'])]
    edges_filtrado = edges_filtrado.to_crs(epsg=32719)
    edges_filtrado.to_file("malla_vial_filtrada.shp")
    print("Archivo filtrado guardado")

# 11. Exportar nodos también
nodes_proj = nodes.to_crs(epsg=32719)
nodes_proj.to_file("nodos_viales_san_miguel.shp")

print("Proceso completado correctamente")

"""Intersecciones críticas (nodos)"""

import osmnx as ox
G = ox.graph_from_place("San Miguel, Santiago, Chile", network_type="drive")
nodes, edges = ox.graph_to_gdfs(G)

# Nodos con alta conectividad
nodos_criticos = nodes[nodes['street_count'] >= 4]